### ISSUE TITLE
brew instal mpd

### ISSUE THREAD

**Issue by geyseran** [Linuxbrew/legacy-linuxbrew#1118]
```
brew install mpd
Error: undefined method `rebuild' for #<BottleSpecification:0x12c3e58>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/pi/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:10:in `block in <class:Autoconf>'
/home/pi/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/pi/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/pi/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:8:in `<class:Autoconf>'
/home/pi/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb:1:in `load_formula'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/pi/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/pi/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/pi/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/pi/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/pi/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/pi/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/pi/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/pi/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/pi/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/pi/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
/home/pi/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
/home/pi/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/pi/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/pi/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/pi/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/pi/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/pi/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/pi/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/pi/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/pi/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/pi/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by sjackman** [comment]
```
Error: undefined method `rebuild'
```
This error indicates that your `brew` is out of date.
Try `brew update` or installing Linuxbrew from scratch.
