### ISSUE TITLE
numpy: builds and installs after standalone brew

### ISSUE THREAD

**Issue by razvanc-r** [Linuxbrew/legacy-linuxbrew#455]
So... I'm having this super annoying time trying to build other stuff after I installed linuxbrew in standalone mode following the guide from the wiki. The build went excellent (for the most part) - had to install Xlib myself but that was fine in the end, just a bit time consuming.

Anyway. Now that I finished installing most parts with `brew install` I wanted to build install python packages with `pip` for example, `numpy`, which gives me:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1h13mstr/numpy/setup.py", line 251, in <module>
        setup_package()
      File "/tmp/pip-build-1h13mstr/numpy/setup.py", line 243, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/build.py", line 39, in run
        old_build.run(self)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/ichec/home/users/razvan/.local/opt/python3/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/build_src.py", line 153, in run
        self.build_sources()
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/build_src.py", line 170, in build_sources
        self.build_extension_sources(ext)
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "/tmp/pip-build-1h13mstr/numpy/numpy/distutils/command/build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 432, in generate_config_h
        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
      File "numpy/core/setup.py", line 42, in check_types
        out = check_types(*a, **kw)
      File "numpy/core/setup.py", line 293, in check_types
        "Cannot compile 'Python.h'. Perhaps you need to "\
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

    ----------------------------------------
/ichec/home/users/razvan/.local/lib/python3.4/site-packages/pip-7.0.3-py3.4.egg/pip/commands/install.py:197: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Command "/ichec/home/users/razvan/.local/opt/python3/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-1h13mstr/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zev6oikk-record/install-record.txt --single-version-externally-managed --compile --prefix= --user" failed with error code 1 in /tmp/pip-build-1h13mstr/numpy
```

How can I instruct things that I want to build to use the `linuxbrew` standalone install?... because it is searching in the wrong places. Another example, I tried building `atom.io`, but with no luck, one module gives me this error:

```
Installing apm...

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /ichec/home/users/razvan/Downloads/atom-master/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/ichec/home/users/razvan/Downloads/atom-master/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/ichec/home/users/razvan/Downloads/atom-master/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

If I use `patchelf` I get:

```
razvan@fionn1:~/Downloads/atom-master> patchelf --set-rpath='$HOME/.local/lib' node script/build 
stat: No such file or directory
```

But I do have `stat`:

```
razvan@fionn1:~/Downloads/atom-master> which stat
/ichec/home/users/razvan/.local/bin/stat
```

Please advise and help? (I also can't use `LD_LIBRARY_PATH` any more cause I get: `razvan@fionn1:~/Downloads/atom-master> LD_LIBRARY_PATH=$HOME/.local/lib node script/build
/bin/sh: error while loading shared libraries: __vdso_time: invalid mode for dlopen(): Invalid argument`)... so I'm kind of stuck.

Thanks!

**Comment by razvanc87** [comment]
So for anyone who's interested, I made a little progress, managed to build and install `numpy` using `pip` with the following command:

```
C_INCLUDE_PATH=build/src.linux-x86_64-3.4/numpy/core/src/private:$HOME/.local/include/python3.4m/:$HOME/.local/include/ LAPACK=$HOME/.local/ BLAS=$HOME/.local/ pip3 install --verbose --user --install-option='--prefix=' nump
```

I've been looking a bit more at the `gcc`'s envirnoment variables and I think I'll experiment next with `CPATH` and `LDFLAGS` (for building `atom` that is, cause this particular one wants to build against the system `glibc` which is why it doesn't work...)

**Comment by sjackman** [comment]
> `patchelf --set-rpath='$HOME/.local/lib' node script/build`

Use double-quotes around `$HOME`. Compare the output of
```sh
echo patchelf --set-rpath='$HOME/.local/lib' node script/build
echo patchelf --set-rpath="$HOME/.local/lib" node script/build
```

**Comment by sjackman** [comment]
Re `C_INCLUDE_PATH`, that's a helpful tip. Thanks!
