### ISSUE TITLE
Error: can't convert Fixnum into String (Ruby 1.8.7)

### ISSUE THREAD

**Issue by sni** [Linuxbrew/legacy-linuxbrew#815]
I get the 

```
Error: can't convert Fixnum into String
```

When i try to install anything.

```
~$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: git://github.com/Homebrew/linuxbrew.git
HEAD: 46013be9b4019b3186ceacf39e0acb636382a269
Last commit: never
HOMEBREW_PREFIX: /home/test/.linuxbrew
HOMEBREW_REPOSITORY: /home/test/.linuxbrew
HOMEBREW_CELLAR: /home/test/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 1.8.7-p72 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.6
Ruby: /usr/bin/ruby
Java: N/A
```

The complete output is:

```
~$ brew install git
==> Installing dependencies for git: xz, pkg-config, makedepend, zlib, gpatch, openssl, curl, expat
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /home/test/.cache/Homebrew/xz-5.2.2.tar.gz
Error: can't convert Fixnum into String
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/lib64/ruby/1.8/fileutils.rb:987:in `fu_get_gid'
/usr/lib64/ruby/1.8/fileutils.rb:926:in `chown'
/home/test/.linuxbrew/Library/Homebrew/extend/fileutils.rb:26:in `mktemp'
/home/test/.linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/home/test/.linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
/home/test/.linuxbrew/Library/Homebrew/formula.rb:1539:in `stage'
/home/test/.linuxbrew/Library/Homebrew/formula.rb:922:in `brew'
/home/test/.linuxbrew/Library/Homebrew/build.rb:108:in `install'
/home/test/.linuxbrew/Library/Homebrew/build.rb:177
```

This is a x64 sles 11 service pack 1.

The relevant part from the mentioned file is:

``` ruby
    begin
      chown(nil, group_id, tmp)
    rescue Errno::EPERM
      opoo "Failed setting group \"#{Etc.getgrgid(group_id).name}\" on #{tmp}"
    end
```

**Comment by sjackman** [comment]
Please report `ruby --version`. If you can, upgrading Ruby will like resolve this issue.

**Comment by sjackman** [comment]
Never mind. Ruby 1.8.7, from above output.

**Comment by sni** [comment]
I comment those lines in fileutils.rb and tried to update ruby, but this fails with:

```
==> Applying mkconfig.patch
patching file tool/mkconfig.rb
==> ./configure --prefix=/home/test/.linuxbrew/Cellar/ruby/2.3.0 --enable-shared --disable-silent-rules --with-sitedir=/home/test/.linuxbrew/l
==> make
Last 15 lines from /home/test/.cache/Homebrew/Logs/ruby/02.make:

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

make: *** [encdb.h] Aborted
make: *** Waiting for unfinished jobs....
/tmp/ruby20160216-11768-hr5o5p/ruby-2.3.0/lib/fileutils.rb:1155:in `rescue in block in touch': uninitialized constant Errno::ENOENT (NameError)
        from /tmp/ruby20160216-11768-hr5o5p/ruby-2.3.0/lib/fileutils.rb:1153:in `block in touch'
        from /tmp/ruby20160216-11768-hr5o5p/ruby-2.3.0/lib/fileutils.rb:1151:in `each'
        from /tmp/ruby20160216-11768-hr5o5p/ruby-2.3.0/lib/fileutils.rb:1151:in `touch'
        from ./tool/mkconfig.rb:298:in `<main>'
rbconfig.rb updated
make: *** [.rbconfig.time] Error 1
```

**Comment by sjackman** [comment]
Please report `brew gist-log ruby`.
You may want to report the bug upstream to Ruby at http://www.ruby-lang.org/bugreport.html

**Comment by sjackman** [comment]
[`chmod`](http://ruby-doc.org/stdlib-1.8.7/libdoc/fileutils/rdoc/FileUtils.html#method-c-chown) is supposed to be able to take an `Integer` or a `String`, so I'm not really sure what's going on here. Sorry. Perhaps it's a bug in Ruby 1.8.7.
Commenting out the `chgrp` line seems a reasonable workaround to install Ruby 2.3.0 using Linuxbrew.

**Comment by maxim-belkin** [comment]
It is `chown`, not `chmod`. The failure happens when it tries to change the `group` of a temporary folder. @sni  can you make sure that you can change group in the `$HOMEBREW_TEMP` folder? Just do: `cd $HOMEBREW_TEMP && mkdir delete_me && chown $USER:<yourgroupname>`? Did you by any change install `coreutils` before that? I have an issue with `coreutils`: after I install it, my `whoami` command returns numbers and it breaks a lot of things...

**Comment by sjackman** [comment]
Typo, sorry. I meant `chown`. It also takes an `Integer` or a `String`.
> Changes owner and group on the named files (in list) to the user user and the group group. user and group may be an ID (Integer/String) or a name (String). If user or group is nil, this method does not change the attribute.
